### ISSUE TITLE
Compilation Error Due to Missing Files

### ISSUE THREAD

**Issue by RSherman15** [splatlab/mantis#2]
When trying to compile mantis, I'm getting an error when trying to make the coloreddbg object (obj/coloreddbg.o). This is due to the fact that there are two includes in coloreddbg.cc for which the files seem to be missing: MantisFS.h and sparsepp/spp.h. 

Should there be a MantisFS file in this repo somewhere, and is sparsepp a separate library which needs to be included (from here I assume via a quick Google search: https://github.com/greg7mdp/sparsepp)?

**Comment by prashantpandey** [comment]
Hello Rachel,

Thanks for bringing the issue to our attention. It seems we missed some files while merging code from the development branch to master. 
We just fixed the issue on the latest commit. Please give it a try. 
And let us know if you see any other issue.

Thanks,
Prashant

**Comment by RSherman15** [comment]
Thanks. Still getting a compilation error but now related to sdsl so it appears the missing file issue was fixed.

It's possible I'm just linking something wrong and the issue is on my end, although I have successfully linked to my build of sdsl when compiling other programs (SSBT) the via inclusion of 
`-L/path/to/sdsl/lib `
in LDFLAGS in the Makefile, so I'm not entirely sure what's going wrong and yielding "undefined reference to sdsl::util and sdsl::osfstream" errors.

**Comment by prashantpandey** [comment]
Yeah, the current Makefile assumes the sdsl lib to be present in the default linking directory. But it seems it's not there. 
Just to make sure that's really the issue can you just comment this line in the Makefile
```
LDFLAGS += $(DEBUG) $(PROFILE) $(OPT) -lsdsl -lpthread -lboost_system \
-lboost_thread -lm -lz -lrt
```
to 
```
LDFLAGS += $(DEBUG) $(PROFILE) $(OPT)  -lpthread -lboost_system \
-lboost_thread -lm -lz -lrt -L/path/to/sdsl/lib
```
and see if it works?

**Comment by rob-p** [comment]
You can also just do : 

```
LDFLAGS=-L/path/to/sdsl/lib make 
```

since the Makefile will add the linker flags to whatever `LDFLAGS` are already present in the environment.

**Comment by RSherman15** [comment]
So interestingly, leaving off -lsdsl entirely produces a different error; I get 
`undefined reference to `sdsl::XXX`
for far more functions (presumably every sdsl function that is called) where as with the library path it's only sdsl::util and sdsl::ofstream. Perhaps I have an outdated version of sdsl or something?

**Comment by prashantpandey** [comment]
Hi Rachel,

The version of sdsl I cloned is from this commit: 

```
commit eb20c308c844c262be597ca5c385e48ef5bc1421
Merge: e681b5f 2ce2c1c
Author: Matthias Petri <Matthias.Petri@gmail.com>
Date:   Sun Oct 22 14:57:17 2017 +0200

    Merge pull request #386 from danielsaad/patch-3
    
    Fixing  sd_vector in order to compile in g++7.2.0
```

Do you have an older version?

Thanks,
Prashant

**Comment by RSherman15** [comment]
I do appear to have an older version - I have the latest "release" which is from 2016. I'll give updating to the newest version a try -- thanks!

**Comment by RSherman15** [comment]
That worked, thanks! You may want to include a required version number/instructions to clone the git repo rather than download the latest release for sdsl in the README since it needs to be more recent than the most recent release - might help others in the future.

**Comment by prashantpandey** [comment]
Great!! And yes, I will add the commit version for sdsl in the readme.

Thanks,
Prashant
